spring:
  application:
    name: ping1
    maxRequestsPerSecond: 2

server:
  port: 8080
  pong:
    url: http://localhost:8090/pong
  lock:
    path: /ping.lock


logging:
  level:
    root: INFO
    com.liuzhijun: DEBUG  # 这里可以指定你的包名，调整日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"  # 控制台日志格式
  file:
    name: logs/${spring.application.name}.log  # 日志文件路径
    pattern: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"  # 日志文件格式